<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="12" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Parameters Testing Test Suite" duration-ms="9281" started-at="2017-12-13T02:25:12Z" finished-at="2017-12-13T02:25:21Z">
    <groups>
    </groups>
    <test name="Parameters Testing" duration-ms="47" started-at="2017-12-13T02:25:12Z" finished-at="2017-12-13T02:25:12Z">
      <class name="com.mits.selenium.testing.ParametersTesting">
        <test-method status="PASS" signature="FillLoginForm(java.lang.String, java.lang.String)[pri:0, instance:com.mits.selenium.testing.ParametersTesting@68be2bc2]" name="FillLoginForm" duration-ms="16" started-at="2017-12-13T10:25:12Z" finished-at="2017-12-13T10:25:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[demo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[PASSWORD]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillLoginForm -->
        <test-method status="PASS" signature="cleaupProcInParamTest()[pri:0, instance:com.mits.selenium.testing.ParametersTesting@68be2bc2]" name="cleaupProcInParamTest" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:12Z" finished-at="2017-12-13T10:25:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleaupProcInParamTest -->
        <test-method status="PASS" signature="OpenBrowser(java.lang.String)[pri:0, instance:com.mits.selenium.testing.ParametersTesting@68be2bc2]" name="OpenBrowser" duration-ms="0" started-at="2017-12-13T10:25:12Z" finished-at="2017-12-13T10:25:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="cleaupProcInParamTest()[pri:0, instance:com.mits.selenium.testing.ParametersTesting@68be2bc2]" name="cleaupProcInParamTest" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:12Z" finished-at="2017-12-13T10:25:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleaupProcInParamTest -->
      </class> <!-- com.mits.selenium.testing.ParametersTesting -->
    </test> <!-- Parameters Testing -->
    <test name="TestNGTesting" duration-ms="9094" started-at="2017-12-13T02:25:12Z" finished-at="2017-12-13T02:25:21Z">
      <class name="com.mits.selenium.testing.SeleniumWebDriverTest">
        <test-method status="PASS" signature="startFireFox()[pri:0, instance:com.mits.selenium.testing.SeleniumWebDriverTest@42d80b78]" name="startFireFox" is-config="true" duration-ms="5835" started-at="2017-12-13T10:25:12Z" finished-at="2017-12-13T10:25:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startFireFox -->
        <test-method status="PASS" signature="MyFirstTestNGTestCase()[pri:0, instance:com.mits.selenium.testing.SeleniumWebDriverTest@42d80b78]" name="MyFirstTestNGTestCase" duration-ms="2586" started-at="2017-12-13T10:25:18Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyFirstTestNGTestCase -->
        <test-method status="PASS" signature="cleaupProc()[pri:0, instance:com.mits.selenium.testing.SeleniumWebDriverTest@42d80b78]" name="cleaupProc" is-config="true" duration-ms="670" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleaupProc -->
      </class> <!-- com.mits.selenium.testing.SeleniumWebDriverTest -->
    </test> <!-- TestNGTesting -->
    <test name="Optional Testing Part1" duration-ms="16" started-at="2017-12-13T02:25:21Z" finished-at="2017-12-13T02:25:21Z">
      <class name="com.mits.selenium.testing.OptionalTesting">
        <test-method status="PASS" signature="optionCheck(java.lang.String)[pri:0, instance:com.mits.selenium.testing.OptionalTesting@685cb137]" name="optionCheck" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Optional Value]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- optionCheck -->
      </class> <!-- com.mits.selenium.testing.OptionalTesting -->
    </test> <!-- Optional Testing Part1 -->
    <test name="Optional Testing Part2" duration-ms="15" started-at="2017-12-13T02:25:21Z" finished-at="2017-12-13T02:25:21Z">
      <class name="com.mits.selenium.testing.OptionalTesting">
        <test-method status="PASS" signature="optionCheck(java.lang.String)[pri:0, instance:com.mits.selenium.testing.OptionalTesting@7d9d1a19]" name="optionCheck" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Provided from XML]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- optionCheck -->
      </class> <!-- com.mits.selenium.testing.OptionalTesting -->
    </test> <!-- Optional Testing Part2 -->
    <test name="DataProviderTest" duration-ms="47" started-at="2017-12-13T02:25:21Z" finished-at="2017-12-13T02:25:21Z">
      <class name="com.mits.selenium.testing.DataProviderTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testMethod(com.mits.selenium.testing.DataProviderTest$JBean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testMethod" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="JavaBeanObjectTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.mits.selenium.testing.DataProviderTest$JBean@d2de489]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method status="PASS" signature="testMethod(com.mits.selenium.testing.DataProviderTest$JBean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testMethod" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="JavaBeanObjectTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.mits.selenium.testing.DataProviderTest$JBean@5a7fe64f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testPrimeNumberChecker(java.lang.Integer, java.lang.Boolean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testPrimeNumberChecker" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="OddDigitTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at com.mits.selenium.testing.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumberChecker -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testPrimeNumberChecker(java.lang.Integer, java.lang.Boolean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testPrimeNumberChecker" duration-ms="15" started-at="2017-12-13T10:25:21Z" data-provider="OddDigitTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at com.mits.selenium.testing.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumberChecker -->
        <test-method status="FAIL" signature="testPrimeNumberChecker(java.lang.Integer, java.lang.Boolean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testPrimeNumberChecker" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="OddDigitTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[false]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at com.mits.selenium.testing.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumberChecker -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testPrimeNumberChecker(java.lang.Integer, java.lang.Boolean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testPrimeNumberChecker" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="OddDigitTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at com.mits.selenium.testing.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumberChecker -->
        <test-method status="FAIL" signature="testPrimeNumberChecker(java.lang.Integer, java.lang.Boolean)[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="testPrimeNumberChecker" duration-ms="0" started-at="2017-12-13T10:25:21Z" data-provider="OddDigitTest" finished-at="2017-12-13T10:25:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at com.mits.selenium.testing.DataProviderTest.testPrimeNumberChecker(DataProviderTest.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrimeNumberChecker -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.mits.selenium.testing.DataProviderTest@204f30ec]" name="initialize" is-config="true" duration-ms="0" started-at="2017-12-13T10:25:21Z" finished-at="2017-12-13T10:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
      </class> <!-- com.mits.selenium.testing.DataProviderTest -->
    </test> <!-- DataProviderTest -->
  </suite> <!-- Parameters Testing Test Suite -->
</testng-results>
